#!/bin/bash

# input_test: a program with varying tests for verifying input from read

read -p "Enter a single item > "

# input is empty
if [[ -z "$REPLY" ]]; then
	echo "Invalid input '$REPLY'" >&2
fi

# input contains multiple items
if (( "$(echo "$REPLY" | wc -w)" > 1 )); then
	echo "Too many items in '$REPLY'." >&2
fi

# is input a valid filename?
if [[ "$REPLY" =~ ^[-[:alnum:]\._]+$ ]]; then
	echo "'$REPLY' is a valid filename."
	if [[ -e "$REPLY" ]]; then 
		echo "And file '$REPLY' exists."
	else 
		echo "However, file '$REPLY' does not exist."
	fi

	#is input a floating point number?
	if [[ "$REPLY" =~ ^-?[[:digit:]]*\.[[:digit:]]+$ ]]; then
		echo "'$REPLY' is a floating point number."
	else
		echo "'$REPLY' is not a floating point number."
	fi

	#is input an integer?
	if [[ "$REPLY" =~ ^-?[[:digit:]]+$ ]]; then
		echo "'$REPLY' is an integer."
	else 
		echo "'$REPLY' is not an integer."
	fi
else 
	echo "The string '$REPLY' is not a valid filename." >&2
fi
