#!/bin/bash

# test_integer: evaluate the value of an integer

read -p "Please enter an integer ->" INT

if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
	if ((INT == 0)); then
		echo "INT is zero."
	else
		if ((INT < 0 )); then
			echo "INT is negative."
		else
			echo "INT is posotive:"
		fi
		if (( ((INT % 2)) == 0 )); then
			echo "INT is even."
		else
			echo "INT is odd."
		fi
	fi
else
	echo "INT is not an integer." >&2
	exit 1
fi
